spring.application.name=core-wallet

spring.datasource.url=jdbc:postgresql://localhost:5432/wallet
spring.datasource.username=wallet_user
spring.datasource.password=wallet_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
